### ISSUE TITLE
HarmonizeR not compatible with R 4.2.1

### ISSUE THREAD

**Issue by BarboraSal** [SimonSchlumbohm/HarmonizR#1]
Hi, I'd like to try your package, but having troubles installing it to the latest R 4.2.1.

**Comment by SimonSchlumbohm** [comment]
Hello BarboraSal,


thank you for the comment. I would still need some additional information to thoroughly adress your problem, so something like your actual error message.

A few things that may already solve your problem:

- If you use install_github() (a function provided by devtools), please try install_github("SimonSchlumbohm/HarmonizR/HarmonizR"), since the package itself lies within the HarmonizR repository (updated in the SOP).

- If it is an error with the installation of dependencies: some dependencies may not be properly updated due to devtools itself depending on them. In this case, please try using install_packages("needed_package") beforehand to install them.

I have tested it on 4.2.1 (on Windows) today. Please feel free to mail me directly if you have further questions.


Best


Simon Schlumbohm

**Comment by BarboraSal** [comment]
Hi Simon, I just successfully installed the package, thanks for your help! Best, Barbora
