### ISSUE TITLE
Cannot reproduce Perseus Plugin SOP

### ISSUE THREAD

**Issue by KR-15** [SimonSchlumbohm/HarmonizR#3]
Hi,

I am currently dealing with an issue regarding the use of the harmonizR plugin on Perseus. 

I followed the Plugin_SOP, everything went well but when I tried to run the R file on Perseus: I get the following error message:

![image](https://user-images.githubusercontent.com/72909968/193777772-9c3f55eb-243b-429e-8131-75eb53b69f3a.png)

What should you recommend ?

Best,

KR

**Comment by SimonSchlumbohm** [comment]
Hello KR,

I used updated versions of the requried libraries (both argparser/PerseusR and all HarmonizR dependencies) and the latest Perseus version, which is 2.0.7.0 (originally the Plugin was implemented under 2.0.3.0). Additionally I use (to my knowledge) the newest, stable R version (4.2.1) as of June 2022. 

Unfortunately, I was unable to reproduce the error, since it works for me under both Perseus 2.0.7.0 and 2.0.3.0.

Please make sure to have all libraries as well as Perseus updated. Also, I recommend R 4.2.1.
Also, please make sure that your path to the Rscript.exe (if under Windows) is set correctly. So something like C:\Program Files\R\R-4.2.1\bin\Rscript.exe (path likely varies for you) and the Select button is green. It might have to be set as a path variable.
Maybe first try it on a randomly generated matrix (like in the SOP) and give no additional arguments.

If you are unable to fix the problem, you can write me directly (schlumbohm@hsu-hh.de).

With best regards

Simon Schlumbohm

**Comment by KR-15** [comment]
Hello Simon,

Sorry, it finally works well. It was a mistake from me. I was using the "R logo" on Perseus (see below).

![image](https://user-images.githubusercontent.com/72909968/195310767-926fa80c-b2f4-4663-9cdb-99fa9d3400e3.png)

 I believed that it was a shortcut of "External/Matrix => R" because the icon looks like exactly the same but it was not the case.

![image](https://user-images.githubusercontent.com/72909968/195310924-07290610-1352-4e78-ba75-f646440a3d4b.png)

Sorry about that and thank you for you help.

Just for information, the plugin work well with Perseus version below 2.0 (I tried on Perseus v1.6.15 and v2.0.3)

Best regards,

KR

**Comment by SimonSchlumbohm** [comment]
Hello KR,

okay, wonderful that it works for you now. I will then close the thread.

Best regards

Simon Schlumbohm
