### ISSUE TITLE
Error in names(x) <- value

### ISSUE THREAD

**Issue by tomonorikaneko** [SimonSchlumbohm/HarmonizR#5]
Hello,

I was trying the HarmonizR Perseus plugin with my data, and got an error. The Perseus Plugin SOP on your website worked fine. Could you please tell me what could be wrong with my file? I attached a screenshot of the error. Please let me know if you'd like me to send the data file. I have 2 groups, 18 main columns and 580 rows in this dataset, with one text column (ID column).

![HarmonizR_error](https://github.com/SimonSchlumbohm/HarmonizR/assets/80800579/702cedfe-1e7f-460f-97da-2d4f8dcfc6f2)

Thank you,
Tomo

**Comment by SimonSchlumbohm** [comment]
Hello @tomonorikaneko 

since it appears to be an error with the column names, I suspect a difference in the sample names between description and the dataset. This can easily happen by accident after modifying data files in excel for example. Potentially, there may also be a difference in length? So more/less columns listed in the description file than in the data. Please refer to the SOP for the HarmonizR itself to verify correct input format.

If the problem lingers on, please feel free to send me the input data and I will try to identify the culprit.
Since I am not available shortly for a while, it might however take a while for me to respond. For that case I would like to apologize in advance.

With best regards

Simon Schlumbohm

**Comment by bioinformatic-guy** [comment]
Hello @SimonSchlumbohm,
I'm facing same issue. I'm using latest version as Perseus Plugin. I removed the duplicate IDs. But Still that error is coming. Using plugin, I just follow the mentioned step in SOP. I'm not putting any descriptive file. Can you help me find out the solution of the issue?
**Even SOP data showing same error** (murine_medulloblastoma_data.tsv)

![image](https://github.com/SimonSchlumbohm/HarmonizR/assets/84230574/f2f62c25-0eb8-4918-abc8-89437359ee4c)
